"""
signal/topic_modeling/lda.py
─────────────────────────────
Stage 3 of the signal pipeline (README §Pipeline 1 — Stage 3).

Two roles (per README):
  1. Fiscal-relevance filtering — assigns each paragraph a posterior
     probability of belonging to the fiscal/monetary topic. Downstream
     scoring stages weight or filter by this probability.
  2. Descriptive validation — topic-word distributions, fiscal-topic
     share by president, and fiscal-filtered word clouds are reported
     as model-free validation exhibits.

Reads
-----
  data/raw/speeches_raw.csv

Writes
------
  data/interim/paragraphs_lda.csv        paragraph-level dataframe with
                                         topic probabilities + fiscal flag
  data/interim/lda/                      saved gensim model, dictionary,
                                         and corpus (for reproducibility)
  outputs/figures/lda_coherence.png      coherence vs k grid-search plot
  outputs/figures/lda_topics.png         top-10 words per topic (best k)
  outputs/figures/lda_fiscal_share.png   fiscal-topic share by president
  (word clouds → run signal/topic_modeling/wordclouds.py separately)
  outputs/lda_validation.html            pyLDAvis interactive browser vis

Config
------
  Adjust NUM_TOPICS_GRID, FISCAL_TOPIC_IDS, and FISCAL_MIN_PROB below.
  On first run, leave FISCAL_TOPIC_IDS = [] — the script auto-detects
  the fiscal topic via seed-word overlap and prints its finding.  Review
  the coherence plot and topic-word chart, then hard-code the relevant
  topic IDs (e.g. FISCAL_TOPIC_IDS = [4, 8]) for reproducibility.
"""

import os
import re
import pickle
import unicodedata
import warnings
from typing import Optional  # retained for other type hints if added later

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")   # non-interactive backend — saves figures without blocking
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

import gensim
from gensim import corpora
from gensim.models import LdaModel, CoherenceModel, Phrases
from gensim.models.phrases import Phraser
import pyLDAvis
import pyLDAvis.gensim_models
# Word clouds are generated by signal/topic_modeling/wordclouds.py

warnings.filterwarnings("ignore", category=DeprecationWarning)

# ── Paths ─────────────────────────────────────────────────────────────────────
_HERE         = os.path.dirname(os.path.abspath(__file__))
_ROOT         = os.path.abspath(os.path.join(_HERE, "..", ".."))
RAW_CSV       = os.path.join(_ROOT, "data", "raw", "speeches_raw.csv")
INTERIM_DIR   = os.path.join(_ROOT, "data", "interim")
LDA_DIR       = os.path.join(INTERIM_DIR, "lda")
FIGURES_DIR   = os.path.join(_ROOT, "outputs", "figures")
OUTPUTS_DIR   = os.path.join(_ROOT, "outputs")

# ── Config ────────────────────────────────────────────────────────────────────
NUM_TOPICS_GRID = list(range(8, 31))    # full sweep k=8–30; fine-grained coherence curve
COHERENCE_METRIC = "c_v"                    # c_v is standard for topic quality
PASSES          = 20                        # LDA training passes
RANDOM_STATE    = 42
MIN_PARA_WORDS  = 20                        # discard very short paragraphs
NO_BELOW        = 5                         # min document frequency
NO_ABOVE        = 0.55                      # max document frequency (fraction)

# ── Phrase detection (bigrams + trigrams) ─────────────────────────────────────
# Gensim Phrases detects collocations like banco_central, ajuste_fiscal,
# libre_mercado that would otherwise be split into ambiguous unigrams.
# min_count : a phrase must appear in at least this many paragraphs to qualify
# threshold : higher = stricter; scored by (count_ab / count_a / count_b) × N
PHRASES_MIN_COUNT = 10   # pair must appear together in ≥10 paragraphs
PHRASES_THRESHOLD = 40   # selectivity gate: high = only genuinely glued pairs

# ── Phrase blacklist ───────────────────────────────────────────────────────────
# Phrases detected by the model but unwanted in LDA topics / word clouds.
# Use the underscore-joined normalised form (e.g. "buenos_aires" not "Buenos Aires").
# Add any geographic, ceremonial, or generic political collocations that
# clutter topics without carrying fiscal or ideological meaning.
PHRASE_BLACKLIST: set[str] = {
    # Argentine cities / regions — geographic noise
    "buenos_aires",
    "ciudad_buenos_aires",
    "mar_plata",
    "rio_negro",
    "santa_fe",
    "san_juan",
    "san_luis",
    "la_plata",
    "tierra_fuego",
    # Common ceremonial / filler bigrams
    "muchas_gracias",
    "muy_bien",
    "muy_importante",
    "por_favor",
    "mas_alla",
    "dia_dia",
    # International proper nouns with no fiscal content
    "america_latina",
    "estados_unidos",
    "naciones_unidas",
    "union_europea",
}

# ── Fiscal topic IDs ──────────────────────────────────────────────────────────
# List every topic whose top words clearly relate to fiscal or monetary policy.
# fiscal_topic_prob in paragraphs_lda.csv = max(topic_i for i in FISCAL_TOPIC_IDS).
#
# WORKFLOW: Leave both lists EMPTY on every new LDA run.  The script will
# train the model, print all topics to stdout AND save them to
# outputs/tables/lda_topic_inspection.txt, then exit.
# Inspect the file, decide which topics are fiscal / ideological,
# then populate the lists below and re-run to produce paragraphs_lda.csv.
#
# There is NO automatic topic detection — assignment is fully manual.
FISCAL_TOPIC_IDS: list[int] = []

# ── Ideology topic IDs ────────────────────────────────────────────────────────
# List topics that capture ideological framing (e.g. libertad, estado, derechos,
# libre mercado) even when explicit fiscal vocabulary is absent.
# ideology_topic_prob in paragraphs_lda.csv = max(topic_i for i in IDEOLOGY_TOPIC_IDS).
# Downstream scoring applies a fractional weight (IDEOLOGY_WEIGHT in
# tfidf_dictionary.py) so ideology paragraphs contribute at partial strength.
IDEOLOGY_TOPIC_IDS: list[int] = []

# Threshold for labelling a paragraph as "fiscal-relevant"
FISCAL_MIN_PROB = 0.25

PRES_ORDER  = ["Macri", "AF", "Milei"]
PRES_COLORS = {"Macri": "#2196F3", "AF": "#4CAF50", "Milei": "#FF5722"}

# ── Stopwords ─────────────────────────────────────────────────────────────────
STOPWORDS_ES = {
    # Articles & prepositions
    "el","la","los","las","un","una","unos","unas",
    "a","ante","bajo","con","contra","de","desde","durante","en","entre",
    "hacia","hasta","para","por","segun","sin","sobre","tras","del","al",
    # Conjunctions
    "e","ni","o","u","que","y","pero","sino","aunque","porque","si",
    "como","cuando","donde","mientras","pues","ya",
    # Pronouns
    "yo","tu","el","ella","nosotros","vosotros","ellos","ellas",
    "me","te","se","nos","os","le","les","lo","les",
    "este","esta","estos","estas","ese","esa","esos","esas",
    "aquel","aquella","aquellos","aquellas","ello",
    "nuestro","nuestra","nuestros","nuestras","su","sus","mi","mis",
    # High-frequency verbs
    "es","son","era","eran","fue","fueron","ser","estar","sido","siendo",
    "ha","han","he","hemos","haber","hay","habia","hubo","habra",
    "tiene","tienen","tener","tenemos","tuvo","tenia","tenian",
    "hace","hacen","hacer","hizo","haria","haran",
    "dijo","dice","decir","dicho","decia",
    "va","van","ir","vamos","vaya","iba","iban",
    "puede","pueden","poder","pudo","podia","podran",
    "quiero","quiere","quieren","querer","queria",
    "sabe","saben","saber","supo",
    # Generic filler
    "no","mas","muy","bien","tambien","ya","solo","aun","asi",
    "aqui","ahi","alli","hoy","ayer","siempre","nunca","antes","despues",
    "todo","todos","toda","todas","cada","mucho","mucha","muchos","muchas",
    "poco","menos","otro","otra","otros","otras","mismo","misma",
    "entonces","bueno","realmente","tan","aca","alla","claro","vez","veces",
    "creo","parece","manera","parte","forma","punto","lugar","momento",
    "cosa","cosas","tipo","caso","casos",
    # Pronouns / demonstratives that slipped through the length filter
    "eso","esto","esos","estos","esa","esas","ese","esos",
    "uno","una","unos","unas","usted","ustedes","estan","esto",
    "voy","vos","van","ver","vez","sea","mil","asi","ahi",
    "sino","pues","bien","aqui","alli","alla","aca","tan",
    "fue","era","han","hay","les","sus","son","ser",
    "aun","mas","nos","por","que","con","del","los","las",
    "esa","ese","eso","esos","esas","uno","unos",
    # Remaining filler caught in fiscal topic top words
    "ademas","tanto","cual","ahora","teniamos","ello","aquello",
    "aquel","cuyo","cuya","cuales","ambos","segun","tras","ante",
    "pro","via","vez","hoy","ayer","tras","luego","sino","recien",
    "pues","vale","claro","obvio","igual","igual","incluso","tampoco",
    # Argentina-specific noise
    "argentina","argentino","argentinos","argentinas","pais","paises",
    "nacion","republica","gobierno","presidente","presidenta",
    "senor","senora","gracias","aplausos","pueblo","hombre","mujer",
    "dia","dias","ano","anos","mes","meses","semana","semanas",
    "mundo","gente","personas","ciudadanos","sociedad",
}

# ── Text helpers ──────────────────────────────────────────────────────────────
_CLEAN_RE = re.compile(r"[^a-z\s]")

def normalise(text: str) -> str:
    text = text.lower()
    text = "".join(
        c for c in unicodedata.normalize("NFD", text)
        if unicodedata.category(c) != "Mn"
    )
    return _CLEAN_RE.sub(" ", text)

def tokenise(text: str) -> list[str]:
    return [
        w for w in normalise(text).split()
        if len(w) >= 3 and w not in STOPWORDS_ES
    ]

# ── Paragraph extraction ──────────────────────────────────────────────────────

def extract_paragraphs(df: pd.DataFrame) -> pd.DataFrame:
    """
    Split each speech into paragraph-level rows.
    Paragraphs are newline-separated chunks of MIN_PARA_WORDS or more words.
    Returns a dataframe with one row per paragraph.
    """
    records = []
    for _, row in df.iterrows():
        lines = str(row["text_raw"]).split("\n")
        for para_idx, line in enumerate(lines):
            line = line.strip()
            if not line:
                continue
            tokens = tokenise(line)
            if len(tokens) < MIN_PARA_WORDS:
                continue
            records.append({
                "speech_id":    row["speech_id"],
                "para_idx":     para_idx,
                "date":         row["date"],
                "president":    row["president"],
                "president_id": row["president_id"],
                "year_month":   row["year_month"],
                "n_tokens":     len(tokens),
                "text_para":    line,
                "tokens":       tokens,
            })
    para_df = pd.DataFrame(records)
    para_df["para_id"] = range(len(para_df))
    return para_df

# ── Coherence grid search ─────────────────────────────────────────────────────

def grid_search_k(
    texts: list[list[str]],
    dictionary: corpora.Dictionary,
    corpus: list,
) -> tuple[int, list[float]]:
    """
    Train LDA for each k in NUM_TOPICS_GRID and return the best k
    and the list of coherence scores.
    """
    scores = []
    print(f"\nCoherence grid search over k = {NUM_TOPICS_GRID}")
    print("-" * 50)
    for k in NUM_TOPICS_GRID:
        model = LdaModel(
            corpus=corpus,
            id2word=dictionary,
            num_topics=k,
            passes=PASSES,
            alpha="auto",
            eta="auto",
            random_state=RANDOM_STATE,
        )
        cm = CoherenceModel(
            model=model,
            texts=texts,
            dictionary=dictionary,
            coherence=COHERENCE_METRIC,
        )
        score = cm.get_coherence()
        scores.append(score)
        print(f"  k={k:2d}  coherence ({COHERENCE_METRIC}) = {score:.4f}")

    best_k = NUM_TOPICS_GRID[int(np.argmax(scores))]
    print(f"\n  Best k = {best_k} (coherence = {max(scores):.4f})")
    return best_k, scores

# ── Topic inspection helper ───────────────────────────────────────────────────

def apply_phrase_blacklist(
    docs: list[list[str]],
    blacklist: set[str],
) -> list[list[str]]:
    """
    Post-process phrase-joined token lists: any token that is in the blacklist
    is split back into its component unigrams.  This runs after Phraser so the
    LDA never sees the blacklisted compound as a single vocabulary term.
    """
    cleaned = []
    for doc in docs:
        new_doc = []
        for token in doc:
            if token in blacklist:
                new_doc.extend(token.split("_"))   # restore unigrams
            else:
                new_doc.append(token)
        cleaned.append(new_doc)
    return cleaned


def print_all_topics(model: LdaModel, n_words: int = 20) -> None:
    """
    Print every topic's top words to stdout AND save to
    outputs/tables/lda_topic_inspection.txt so the researcher can decide
    which IDs to assign to FISCAL_TOPIC_IDS and IDEOLOGY_TOPIC_IDS.
    Called automatically when either list is empty after training.
    """
    k = model.num_topics
    lines = []
    lines.append("=" * 70)
    lines.append(f"  LDA TOPIC INSPECTION  (k={k}, top {n_words} words each)")
    lines.append(f"  Set FISCAL_TOPIC_IDS and IDEOLOGY_TOPIC_IDS in lda.py,")
    lines.append(f"  then re-run to produce paragraphs_lda.csv.")
    lines.append("=" * 70)
    for i in range(k):
        words = [w for w, _ in model.show_topic(i, topn=n_words)]
        lines.append(f"  Topic {i:2d}: {words}")
    lines.append("=" * 70)

    block = "\n".join(lines)
    print(f"\n{block}\n")

    tables_dir = os.path.join(OUTPUTS_DIR, "tables")
    os.makedirs(tables_dir, exist_ok=True)
    out_path = os.path.join(tables_dir, "lda_topic_inspection.txt")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(block + "\n")
    print(f"  → Saved: {out_path}")

# ── Plots ─────────────────────────────────────────────────────────────────────

def plot_coherence(scores: list[float]):
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(NUM_TOPICS_GRID, scores, marker="o", color="steelblue", linewidth=2)
    best_k = NUM_TOPICS_GRID[int(np.argmax(scores))]
    ax.axvline(best_k, color="red", linestyle="--", linewidth=1.2,
               label=f"Best k={best_k}")
    ax.set_xlabel("Number of topics (k)")
    ax.set_ylabel(f"Coherence ({COHERENCE_METRIC})")
    ax.set_title("LDA coherence grid search")
    ax.set_xticks(NUM_TOPICS_GRID)
    ax.legend()
    plt.tight_layout()
    path = os.path.join(FIGURES_DIR, "lda_coherence.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved: {path}")


def plot_topic_words(model: LdaModel, fiscal_topic_id: Optional[int] = None, n_words: int = 10):
    k = model.num_topics
    cols = min(k, 4)
    rows = (k + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 4, rows * 3))
    axes = np.array(axes).flatten()

    for i in range(k):
        words, weights = zip(*model.show_topic(i, topn=n_words))
        color = "#FF5722" if (fiscal_topic_id is not None and i == fiscal_topic_id) else "steelblue"
        axes[i].barh(list(words)[::-1], list(weights)[::-1], color=color)
        label = " ★ FISCAL" if (fiscal_topic_id is not None and i == fiscal_topic_id) else ""
        axes[i].set_title(f"Topic {i}{label}", fontsize=9)
        axes[i].tick_params(axis="y", labelsize=7)
        axes[i].tick_params(axis="x", labelsize=7)

    for j in range(k, len(axes)):
        axes[j].set_visible(False)

    plt.suptitle(f"Top {n_words} words per topic (k={k}, fiscal=Topic {fiscal_topic_id})",
                 fontsize=11)
    plt.tight_layout()
    path = os.path.join(FIGURES_DIR, "lda_topics.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved: {path}")


def plot_fiscal_share(para_df: pd.DataFrame):
    share = (
        para_df[para_df["president"].isin(PRES_ORDER)]
        .groupby(["president", "year_month"])
        ["is_fiscal"].mean()
        .reset_index()
    )
    share["ym_dt"] = pd.to_datetime(share["year_month"])

    fig, ax = plt.subplots(figsize=(16, 3))
    for pres in PRES_ORDER:
        sub = share[share["president"] == pres].sort_values("ym_dt")
        ax.plot(sub["ym_dt"], sub["is_fiscal"],
                label=pres, color=PRES_COLORS[pres], linewidth=1.2)

    ax.set_title(f"Fiscal-topic paragraph share by month (threshold={FISCAL_MIN_PROB})")
    ax.set_ylabel("Fraction of paragraphs")
    ax.legend()
    plt.tight_layout()
    path = os.path.join(FIGURES_DIR, "lda_fiscal_share.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved: {path}")


# Word cloud generation lives in signal/topic_modeling/wordclouds.py
# Run it independently after lda.py has produced paragraphs_lda.csv:
#   python signal/topic_modeling/wordclouds.py

# ── Main ──────────────────────────────────────────────────────────────────────

def run(
    fiscal_topic_ids: list[int] = FISCAL_TOPIC_IDS,
    ideology_topic_ids: list[int] = IDEOLOGY_TOPIC_IDS,
):
    for d in [INTERIM_DIR, LDA_DIR, FIGURES_DIR, OUTPUTS_DIR]:
        os.makedirs(d, exist_ok=True)

    # ── 1. Load and extract paragraphs ────────────────────────────────────────
    print("Loading speeches...")
    df = pd.read_csv(RAW_CSV, parse_dates=["date"])
    df = df[df["president"].isin(PRES_ORDER)]
    print(f"  {len(df)} speeches from Macri / AF / Milei")

    print("\nExtracting paragraphs...")
    para_df = extract_paragraphs(df)
    print(f"  {len(para_df):,} paragraphs (≥{MIN_PARA_WORDS} tokens)")

    texts = para_df["tokens"].tolist()

    # ── 1b. Detect bigrams and trigrams ───────────────────────────────────────
    print("\nDetecting phrases (bigrams → trigrams)...")
    bigram_model  = Phrases(texts,
                            min_count=PHRASES_MIN_COUNT,
                            threshold=PHRASES_THRESHOLD)
    trigram_model = Phrases(bigram_model[texts],
                            min_count=PHRASES_MIN_COUNT,
                            threshold=PHRASES_THRESHOLD)
    bigram  = Phraser(bigram_model)
    trigram = Phraser(trigram_model)

    texts = [trigram[bigram[doc]] for doc in texts]

    # Apply blacklist — split unwanted phrases back into unigrams
    texts = apply_phrase_blacklist(texts, PHRASE_BLACKLIST)

    # Spot-check: print the 40 most common detected phrases
    from collections import Counter
    phrase_counts: Counter = Counter()
    for doc in texts:
        phrase_counts.update(t for t in doc if "_" in t)
    top_phrases = phrase_counts.most_common(40)
    print(f"  Top 40 detected phrases (after blacklist):")
    for phrase, count in top_phrases:
        print(f"    {count:5d}  {phrase}")

    # Save phrase models for reproducibility
    bigram_model.save( os.path.join(LDA_DIR, "bigram_model"))
    trigram_model.save(os.path.join(LDA_DIR, "trigram_model"))
    print(f"  Phrase models saved to {LDA_DIR}/")

    # ── 2. Build dictionary and corpus ────────────────────────────────────────
    print("\nBuilding vocabulary...")
    dictionary = corpora.Dictionary(texts)
    print(f"  Vocabulary before filtering: {len(dictionary):,} terms")
    dictionary.filter_extremes(no_below=NO_BELOW, no_above=NO_ABOVE)
    print(f"  Vocabulary after filtering : {len(dictionary):,} terms")
    corpus = [dictionary.doc2bow(t) for t in texts]

    # ── 3. Grid search over k ─────────────────────────────────────────────────
    best_k, coherence_scores = grid_search_k(texts, dictionary, corpus)
    plot_coherence(coherence_scores)

    # ── 4. Train final model with best k and auto α/β ─────────────────────────
    print(f"\nTraining final model (k={best_k}, α=auto, η=auto)...")
    lda = LdaModel(
        corpus=corpus,
        id2word=dictionary,
        num_topics=best_k,
        passes=PASSES,
        alpha="auto",
        eta="auto",
        random_state=RANDOM_STATE,
    )

    # ── 5. Validate topic ID assignments ─────────────────────────────────────
    # No auto-detection — researcher inspects topics and sets IDs manually.
    if not fiscal_topic_ids:
        # Save topic chart (no highlight) so user can inspect visually,
        # then print the word table and exit.
        plot_topic_words(lda, fiscal_topic_id=None)
        print_all_topics(lda)
        raise SystemExit(
            "\nDone.  Inspect:\n"
            "  outputs/figures/lda_topics.png\n"
            "  outputs/tables/lda_topic_inspection.txt\n"
            "Then set FISCAL_TOPIC_IDS (and optionally IDEOLOGY_TOPIC_IDS)\n"
            "in lda.py and re-run to produce paragraphs_lda.csv."
        )

    print(f"\nFiscal topic IDs  : {fiscal_topic_ids}")
    for tid in fiscal_topic_ids:
        print(f"  Topic {tid}: {[w for w, _ in lda.show_topic(tid, topn=12)]}")

    if ideology_topic_ids:
        print(f"\nIdeology topic IDs: {ideology_topic_ids}")
        for tid in ideology_topic_ids:
            print(f"  Topic {tid}: {[w for w, _ in lda.show_topic(tid, topn=12)]}")
    else:
        print("\nIdeology topic IDs: [] (not set — ideology_topic_prob will be 0.0)")

    # Plot with first fiscal topic highlighted
    plot_topic_words(lda, fiscal_topic_ids[0])

    # ── 6. Compute per-paragraph topic probabilities ──────────────────────────
    print("\nComputing per-paragraph topic probabilities...")
    topic_probs = []
    for bow in corpus:
        doc_topics = dict(lda.get_document_topics(bow, minimum_probability=0.0))

        # Fiscal probability: max across all designated fiscal/monetary topic IDs.
        # Max (not sum) keeps the value in [0,1] and avoids double-weighting.
        fiscal_prob = max(doc_topics.get(tid, 0.0) for tid in fiscal_topic_ids)

        # Ideology probability: max across all designated ideology topic IDs.
        # Stored separately so tfidf_dictionary.py can apply a fractional weight.
        ideology_prob = (
            max(doc_topics.get(tid, 0.0) for tid in ideology_topic_ids)
            if ideology_topic_ids else 0.0
        )

        topic_probs.append({
            **{f"topic_{i}": doc_topics.get(i, 0.0) for i in range(best_k)},
            "fiscal_topic_prob":   fiscal_prob,
            "ideology_topic_prob": ideology_prob,
        })

    prob_df = pd.DataFrame(topic_probs)
    para_df = pd.concat([para_df.reset_index(drop=True), prob_df], axis=1)
    para_df["is_fiscal"]   = para_df["fiscal_topic_prob"]   >= FISCAL_MIN_PROB
    para_df["is_ideology"] = para_df["ideology_topic_prob"] >= FISCAL_MIN_PROB
    para_df.drop(columns=["tokens"], inplace=True)

    print(f"  Fiscal paragraphs    (prob ≥ {FISCAL_MIN_PROB}): "
          f"{para_df['is_fiscal'].sum():,} / {len(para_df):,} "
          f"({para_df['is_fiscal'].mean()*100:.1f}%)")
    if ideology_topic_ids:
        print(f"  Ideology paragraphs  (prob ≥ {FISCAL_MIN_PROB}): "
              f"{para_df['is_ideology'].sum():,} / {len(para_df):,} "
              f"({para_df['is_ideology'].mean()*100:.1f}%)")

    # ── 7. Save outputs ───────────────────────────────────────────────────────
    out_csv = os.path.join(INTERIM_DIR, "paragraphs_lda.csv")
    para_df.to_csv(out_csv, index=False)
    print(f"\nSaved paragraph dataframe: {out_csv}")

    lda.save(os.path.join(LDA_DIR, "lda_model"))
    dictionary.save(os.path.join(LDA_DIR, "dictionary"))
    with open(os.path.join(LDA_DIR, "corpus.pkl"), "wb") as f:
        pickle.dump(corpus, f)
    print(f"Saved model artefacts: {LDA_DIR}/")

    # ── 8. pyLDAvis ──────────────────────────────────────────────────────────
    print("\nGenerating pyLDAvis...")
    vis = pyLDAvis.gensim_models.prepare(lda, corpus, dictionary, sort_topics=False)
    vis_path = os.path.join(OUTPUTS_DIR, "lda_validation.html")
    pyLDAvis.save_html(vis, vis_path)
    print(f"Saved interactive vis: {vis_path}")

    # ── 9. Descriptive plots ──────────────────────────────────────────────────
    print("\nGenerating descriptive plots...")
    plot_fiscal_share(para_df)
    print("\nWord clouds → run separately: python signal/topic_modeling/wordclouds.py")

    # ── 10. Summary ───────────────────────────────────────────────────────────
    pres_paras = para_df[para_df["president"].isin(PRES_ORDER)]
    fiscal_share = (
        pres_paras.groupby("president")["is_fiscal"]
        .agg(["sum", "count", "mean"])
        .rename(columns={"sum": "fiscal", "count": "total", "mean": "share"})
    )
    ideology_share = (
        pres_paras.groupby("president")["is_ideology"]
        .agg(["sum", "mean"])
        .rename(columns={"sum": "ideology", "mean": "ideology_share"})
    )

    def _topic_word_lines(ids, label):
        lines = []
        for tid in ids:
            words = [w for w, _ in lda.show_topic(tid, topn=10)]
            lines.append(f"  Topic {tid} ({label}) top words : {words}")
        return lines

    summary_lines = [
        "=== LDA SUMMARY ===",
        f"Best k              : {best_k}",
        f"Fiscal topic IDs    : {fiscal_topic_ids}",
        "  fiscal_topic_prob  = max(topic_i for i in FISCAL_TOPIC_IDS)",
        f"Ideology topic IDs  : {ideology_topic_ids}",
        "  ideology_topic_prob= max(topic_i for i in IDEOLOGY_TOPIC_IDS)",
    ] + _topic_word_lines(fiscal_topic_ids, "fiscal") \
      + _topic_word_lines(ideology_topic_ids, "ideology") + [
        f"Fiscal paragraphs   : {para_df['is_fiscal'].sum():,} / {len(para_df):,} "
        f"({para_df['is_fiscal'].mean()*100:.1f}%)",
        f"Ideology paragraphs : {para_df['is_ideology'].sum():,} / {len(para_df):,} "
        f"({para_df['is_ideology'].mean()*100:.1f}%)",
        f"Coherence metric    : {COHERENCE_METRIC}",
        f"Fiscal threshold    : {FISCAL_MIN_PROB}",
        "",
        "Fiscal paragraph share by president:",
        fiscal_share.to_string(),
        "",
        "All topic top words:",
    ]
    for i in range(best_k):
        top = [w for w, _ in lda.show_topic(i, topn=10)]
        if i in fiscal_topic_ids:
            tag = " ← FISCAL"
        elif i in ideology_topic_ids:
            tag = " ← IDEOLOGY"
        else:
            tag = ""
        summary_lines.append(f"  Topic {i:2d}{tag}: {top}")

    # Append paragraph share tables
    summary_lines += [
        "",
        "Fiscal paragraph share by president:",
        fiscal_share.to_string(),
        "",
        "Ideology paragraph share by president:",
        ideology_share.to_string(),
    ]

    summary_text = "\n".join(summary_lines)
    print("\n" + summary_text)

    # Save to outputs/tables/
    tables_dir = os.path.join(_ROOT, "outputs", "tables")
    os.makedirs(tables_dir, exist_ok=True)
    summary_path = os.path.join(tables_dir, "lda_summary.txt")
    with open(summary_path, "w") as f:
        f.write(summary_text)
    print(f"\nSaved summary: {summary_path}")

    fiscal_share.join(ideology_share).to_csv(
        os.path.join(tables_dir, "lda_fiscal_share.csv")
    )
    print(f"Saved fiscal/ideology share table: {tables_dir}/lda_fiscal_share.csv")

    return lda, para_df


if __name__ == "__main__":
    lda, para_df = run()
